# Generated by Django 2.2.15 on 2020-10-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_icon', '0002_auto_20190218_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='font size'),
        ),
    ]
